apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccu3-backup.fullname" . }}
type: Opaque
stringData:
  MINIO_ACCESS_KEY: {{ .Values.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minioAccessSecret | quote }}
  HOMEMATIC_USERNAME: {{ .Values.homematicUsername | quote }}
  HOMEMATIC_PASSWORD: {{ .Values.homematicPassword | quote }}